### ISSUE TITLE
I do not get it working

### ISSUE THREAD

**Issue by erc94** [fadden/android-audio-bypass#1]
What is the path to the plugin folder? I do not get it working. Could you give me a little instruction to use? Thank you

**Comment by fadden** [comment]
Are you looking for a compiled version of AudioBypassPlugin.jar, or are you just looking for the folder to put it in (Assets\Plugins\Android in your Unity project)?

**Comment by erc94** [comment]
If I load the project folder tells me this in the console: "Rebuilding Library because the asset database could not be found!", I don't know where to place the plugin folder, and testscene is empty, do not know what I'm doing wrong. Forgive these questions rookie and my bad English.

**Comment by fadden** [comment]
The "rebuilding Library" message is expected.  You should be able to double-click Assets/TestScene from within Unity to see the scene.  (Or double-click TestScene.unity from Windows explorer to open Unity with the scene selected.)

I tried it just now by downloading "Source code (zip)" from the releases page (https://github.com/fadden/android-audio-bypass/releases).

A pre-built copy of the plugin is included, so there's no need to build that part unless you're making changes.  You can find it in AudioBypassTest\Assets\Plugins\Android\AudioBypassPlugin.jar.

Hit ctrl-shift-B, and make sure you're configured to build for Android.  Hit "build".  Install the APK on an Android device.

**Comment by erc94** [comment]
Sorry, I was using Unity version 4.1, I downloaded version 5.1 and it works all right. Thank you very much and sorry for the inconvenience!

**Comment by cricketjoeara** [comment]
hi, can u tell me how to add volume slider to this plugin?
please. btw Thanks for this plugin bro :)

**Comment by fadden** [comment]
BypassAudioSource has an "m_volume" field that can be set per source.

If you want a global volume setting you'll need to add a call to the plugin to set it, and then multiply the global volume \* the left/right volume settings in the Java-side play() call.

**Comment by cricketjoeara** [comment]
Thanks for the reply. i know the point, but i dont understant how to make the script call in the java-side play(). i am newbi here. can u write for me please? so i can learn.

**Comment by cricketjoeara** [comment]
ahaa i got it. thanks
